NUMBER ::= DECIMAL |
           HEX |
           BINARY

DECIMAL ::= [0-9]+
HEX ::= '0x' [0-9a-fA-F]+
BINARY ::= '0b' [0-1]+

IDENTIFIER ::= [a-z][A-Z_] [a-zA-Z0-9_]*

IF ::= 'if'

WHILE ::= 'while'
PLUS ::= '+'

SUB ::= '-'

MULT ::= '*' 

DIV ::= '/'

EQ ::= '='

LSQBRACK ::= = '['

RSQBRACK ::= ']'

COMMA ::= ','

UNDERSCORE ::= '_'

number_list ::= NUMBER number_list

list ::= LSQBRACK number_list RSQBRACK |
        LSQBRACK RSQBRACK

statement ::= IDENTIFIER EQ NUMBER |
               IDENTIFIER EQ IDENTIFIER |
               IDENTIFIER LSQBRACK NUMBER RSQBRACK |
               IDENTIFIER LSQBRACK NUMBER RSQBRACK EQ NUMBER
               ;

expression